
"use client";

import { Bar, BarChart, ResponsiveContainer, XAxis, YAxis, Tooltip, Cell } from "recharts";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { ChartContainer, ChartTooltipContent } from "@/components/ui/chart";

const data = [
    { cluster: "MECH", alerts: 8, fill: "hsl(140 80% 40%)" },
    { cluster: "ECE", alerts: 2, fill: "hsl(var(--destructive))" },
    { cluster: "EEE", alerts: 12, fill: "hsl(var(--chart-5))" },
    { cluster: "CSE", alerts: 1, fill: "hsl(var(--chart-1))" },
];

const chartConfig = {
  alerts: {
    label: "Alerts",
  },
};

export function AlertsPerClusterChart() {
  return (
    <Card>
      <CardHeader>
        <CardTitle>Alerts Per Cluster</CardTitle>
        <CardDescription>Total number of alerts generated by each cluster.</CardDescription>
      </CardHeader>
      <CardContent>
        <ChartContainer config={chartConfig} className="h-[300px] w-full">
          <ResponsiveContainer width="100%" height="100%">
            <BarChart data={data}>
              <Tooltip
                cursor={false}
                content={<ChartTooltipContent hideLabel />}
              />
              <XAxis
                dataKey="cluster"
                tickLine={false}
                axisLine={false}
                tickMargin={8}
                className="text-sm"
              />
              <YAxis tickLine={false} axisLine={false} />
              <Bar dataKey="alerts" radius={4}>
                {data.map((entry) => (
                    <Cell key={`cell-${entry.cluster}`} fill={entry.fill} />
                ))}
              </Bar>
            </BarChart>
          </ResponsiveContainer>
        </ChartContainer>
      </CardContent>
    </Card>
  );
}
